const projectsDatabase = [
  {
    id: 1,
    name: 'Сапер',
    description: 'Игра сапер',
    img: '01_MS.png',
    gitlink: 'https://github.com/Sverkhchelovek92/Minesweeper',
  },
  {
    id: 2,
    name: 'Filament',
    description: 'Веб-сайт для видеопродакшена',
    img: '02_F.png',
    gitlink: 'https://github.com/Sverkhchelovek92/Filament-Web',
  },
  {
    id: 3,
    name: 'Cool-Buy',
    description: 'Тестовый интернет магазин',
    img: '03_CB.png',
    gitlink: 'https://github.com/Sverkhchelovek92/Filament-Web',
  },
  {
    id: 4,
    name: 'To-Do-To-Do List',
    description: 'Список задач, где можно создавать подзадачи',
    img: '04_TD.png',
    gitlink: 'https://github.com/Sverkhchelovek92/To-Do-To-Do-List',
  },
  {
    id: 5,
    name: 'Savewatch',
    description: 'Секундомер с возможностью сохранять время',
    img: '05_SW.png',
    gitlink: 'https://github.com/Sverkhchelovek92/Savewatch',
  },
  {
    id: 6,
    name: 'Random Number Generator',
    description: 'Генератор случайных чисел',
    img: '06_RN.png',
    gitlink: 'https://github.com/Sverkhchelovek92/random-number',
  },
  {
    id: 7,
    name: "Conway's Game of Life",
    description: `Простой симулятор игры "Жизнь"`,
    img: '07_C.png',
    gitlink: 'https://github.com/Sverkhchelovek92/Conway-s-Game-of-Life',
  },
  {
    id: 8,
    name: 'Wordborne',
    description: 'Генератор слов',
    img: '08_W.png',
    gitlink: 'https://github.com/Sverkhchelovek92/Wordborne',
  },
  {
    id: 9,
    name: 'Weather App',
    description: 'Прогноз погоды',
    img: '09_W.png',
    gitlink: 'https://github.com/Sverkhchelovek92/Weather-App',
  },
  {
    id: 10,
    name: 'Monty Hall',
    description: 'Простая игра основанная на проблеме Монти Холла',
    img: '10_M.png',
    gitlink: 'https://github.com/Sverkhchelovek92/Monty-Hall',
  },
  {
    id: 11,
    name: 'Rotating Cube',
    description: '3D Куб, у которого можно менять цвет и скорость вращения',
    img: '11_C.png',
    gitlink: 'https://github.com/Sverkhchelovek92/Rotating-Cube',
  },
  {
    id: 12,
    name: 'Data Visualizer',
    description: 'Приложение, которое строит графики',
    img: '12_DV.png',
    gitlink: 'https://github.com/Sverkhchelovek92/Charts',
  },
  {
    id: 13,
    name: 'Code Rain',
    description: `Дождь из символов, как в фильме "Матрица"`,
    img: '13_CR.png',
    gitlink: 'https://github.com/Sverkhchelovek92/Coderain',
  },
]

export default projectsDatabase
